# permissions for end users to edit charactercounters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: charactercounter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-v2
    app.kubernetes.io/part-of: operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: charactercounter-editor-role
rules:
- apiGroups:
  - ramp-up.joe.ionos.io
  resources:
  - charactercounters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramp-up.joe.ionos.io
  resources:
  - charactercounters/status
  verbs:
  - get
