// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: character-counter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type CountCharactersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CountCharactersRequest) Reset() {
	*x = CountCharactersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_character_counter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountCharactersRequest) ProtoMessage() {}

func (x *CountCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_counter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountCharactersRequest.ProtoReflect.Descriptor instead.
func (*CountCharactersRequest) Descriptor() ([]byte, []int) {
	return file_character_counter_proto_rawDescGZIP(), []int{0}
}

func (x *CountCharactersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type CountCharactersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CountCharactersResponse) Reset() {
	*x = CountCharactersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_character_counter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountCharactersResponse) ProtoMessage() {}

func (x *CountCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_counter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountCharactersResponse.ProtoReflect.Descriptor instead.
func (*CountCharactersResponse) Descriptor() ([]byte, []int) {
	return file_character_counter_proto_rawDescGZIP(), []int{1}
}

func (x *CountCharactersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_character_counter_proto protoreflect.FileDescriptor

var file_character_counter_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2d, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x72, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x64, 0x22, 0x2c, 0x0a, 0x16, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x33, 0x0a, 0x17, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x6c, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x58, 0x0a, 0x0f, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x12, 0x20, 0x2e,
	0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_character_counter_proto_rawDescOnce sync.Once
	file_character_counter_proto_rawDescData = file_character_counter_proto_rawDesc
)

func file_character_counter_proto_rawDescGZIP() []byte {
	file_character_counter_proto_rawDescOnce.Do(func() {
		file_character_counter_proto_rawDescData = protoimpl.X.CompressGZIP(file_character_counter_proto_rawDescData)
	})
	return file_character_counter_proto_rawDescData
}

var file_character_counter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_character_counter_proto_goTypes = []interface{}{
	(*CountCharactersRequest)(nil),  // 0: frontend.CountCharactersRequest
	(*CountCharactersResponse)(nil), // 1: frontend.CountCharactersResponse
}
var file_character_counter_proto_depIdxs = []int32{
	0, // 0: frontend.CharacterCounter.CountCharacters:input_type -> frontend.CountCharactersRequest
	1, // 1: frontend.CharacterCounter.CountCharacters:output_type -> frontend.CountCharactersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_character_counter_proto_init() }
func file_character_counter_proto_init() {
	if File_character_counter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_character_counter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountCharactersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_character_counter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountCharactersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_character_counter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_character_counter_proto_goTypes,
		DependencyIndexes: file_character_counter_proto_depIdxs,
		MessageInfos:      file_character_counter_proto_msgTypes,
	}.Build()
	File_character_counter_proto = out.File
	file_character_counter_proto_rawDesc = nil
	file_character_counter_proto_goTypes = nil
	file_character_counter_proto_depIdxs = nil
}
