run:
  timeout: 5m

issues:
  exclude-rules:
    # temporary solution to prevent golanci-lint fix from removing the
    # Kubebuilder specific marker comment due to bug in gci
    - path: main\.go
      linters:
        - gci

linters:
  enable:
    - bodyclose
    - dupl
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - gosec
    - importas
    - lll
    - loggercheck
    - misspell
    - nilerr
    - nosprintfhostport
    - revive
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/jonas27/ramp-up-k8s-operator)
  importas:
    no-unaliased: true
    alias:
      - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
  loggercheck:
    require-string-key: true
    no-printf-like: true
