version: "3"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  manifest:
    desc: Reproduce manifests
    cmds:
      - make generate
      - make manifests
      - make install

  lint:
    desc: Lint all go files in DIR.
    cmds:
      - golangci-lint run --timeout 10m0s --fix internal/...

  test:
    desc: Test all go files in DIR.
    cmds:
      - go test ./...
      - task: lint

  run:
    desc: Run operator in current context
    cmds:
      - make run

  apply:
    desc: apply test crd
    cmds:
      - task manifest && kubectl replace --force -f test.yaml

  port-forward:
    desc: port-forward the frontend
    cmds:
      - kubectl port-forward service/frontend 8000:80 -n test

  load-images:
    desc: load local images into kind
    cmds:
      - kind load docker-image ramp-up-k8s-operator/frontend:v0.0.1
      - kind load docker-image ramp-up-k8s-operator/server:v0.0.1
